[package]
name = "tiktoken-node"
version = "0.0.8"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon = "1.7.0"
napi = "2"
napi-derive = "2"
tiktoken-rs = "0.5.9"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
